---
title: "AWS25 Data Explorer"
author: "LiquidFruit"
date: "`r Sys.Date()`"
output:
  html_document
---

```{r echo=FALSE, include=FALSE}
# global options
plotly_colorscale = "Jet"
season_order = c("10_2021", "11_2021", "12_2021", "01_2022", "02_2022", "03_2022", "04_2022", "05_2022", "06_2022", "07_2022", "08_2022", "09_2022", "10_2022", "11_2022", "12_2022", "01_2023", "02_2023", "03_2023", "04_2023", "05_2023", "06_2023", "07_2023", "08_2023", "09_2023", "10_2023", "11_2023")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readxl)
library(writexl)
library(plotly)
library(ggplot2)
library(DT)

#setwd to currently executing script location
args <- commandArgs(trailingOnly = TRUE)
if (length(args) > 0) {
  script_path <- normalizePath(args[1])
  script_dir <- dirname(script_path)
  setwd(script_dir)
}
```

```{r echo=FALSE}
# load data
all_data = read_excel("../data/processed_data/season_stats.xlsx")
```

# All Data
```{r echo=FALSE}
datatable_data = all_data %>% select(Name, Tag, Season, Clan, Attacks, Donated, Activity_Score, Received, War_Stars, CWL_Stars, Gold, Elixir, Dark_Elixir, Clan_Games, Capital_Gold_Looted, Capital_Gold_Donated, Discord)
datatable(datatable_data, selection = 'none', extensions = c('Buttons', 'Select'), options = list(
  lengthMenu = list(c(1, 5, 10, 25, 50, -1), c('1', '5', '10', '25', '50', 'All')),
  pageLength = 5,
  dom = 'Blfrtip',
  scrollX = TRUE,
  autoWidth = FALSE,
  searchHighlight = TRUE,
  buttons = list(
        list(
          extend = "copy",
          text = 'Copy',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "csv",
          text = 'CSV',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "excel",
          text = 'Excel',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        )
      )
)
)
```

# Only Adult
```{r echo=FALSE}
adult_datatable_data = datatable_data %>% filter(Clan == "Adult")
datatable(adult_datatable_data, selection = 'none', extensions = c('Buttons', 'Select'), options = list(
  lengthMenu = list(c(1, 5, 10, 25, 50, -1), c('1', '5', '10', '25', '50', 'All')),
  pageLength = 5,
  dom = 'Blfrtip',
  scrollX = TRUE,
  autoWidth = FALSE,
  searchHighlight = TRUE,
  columnDefs = list(list(width = '200px', targets = "_all")),
  buttons = list(
        list(
          extend = "copy",
          text = 'Copy',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "csv",
          text = 'CSV',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "excel",
          text = 'Excel',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        )
      )
)
)
```

# Only MOU
```{r echo=FALSE}
mou_datatable_data = datatable_data %>% filter(Clan == "MOU")
datatable(mou_datatable_data, selection = 'none', extensions = c('Buttons', 'Select'), options = list(
  lengthMenu = list(c(1, 5, 10, 25, 50, -1), c('1', '5', '10', '25', '50', 'All')),
  pageLength = 5,
  dom = 'Blfrtip',
  scrollX = TRUE,
  autoWidth = FALSE,
  searchHighlight = TRUE,
  buttons = list(
        list(
          extend = "copy",
          text = 'Copy',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "csv",
          text = 'CSV',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "excel",
          text = 'Excel',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        )
      )
)
)
```

# Lifetime Stats Across All Seasons
```{r echo=FALSE, warning=FALSE, message=FALSE}
lifetime_datatable_data = datatable_data %>% group_by(Name, Tag) %>% summarise(Total_Attacks = sum(Attacks), Total_Donations = sum(Donated), Total_Activity_Score = sum(Activity_Score), Total_Received = sum(Received), Total_Dark_Elixir = sum(Dark_Elixir), Total_Clan_Games = sum(Clan_Games), Total_Capital_Gold_Looted = sum(Capital_Gold_Looted), Total_Capital_Gold_Donated = sum(Capital_Gold_Donated))

datatable(lifetime_datatable_data, selection = 'none', extensions = c('Buttons', 'Select'), options = list(
  lengthMenu = list(c(1, 5, 10, 25, 50, -1), c('1', '5', '10', '25', '50', 'All')),
  pageLength = 5,
  dom = 'Blfrtip',
  scrollX = TRUE,
  autoWidth = FALSE,
  searchHighlight = TRUE,
  buttons = list(
        list(
          extend = "copy",
          text = 'Copy',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "csv",
          text = 'CSV',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        ), 
        list(
          extend = "excel",
          text = 'Excel',
          exportOptions = list(modifier = list(visible = TRUE), rows = ":visible", columns = ":visible")
        )
      )
)
)
```

```{r echo=FALSE, include=FALSE}
# example plotly plot
activity = all_data %>%
  group_by(Name) %>%
  summarise(Activity = sum(Activity_Score))
plot_ly(activity, x=~Name, y=~Activity, type="bar", marker = list(color = ~Activity, colorscale = plotly_colorscale))
```

```{r echo=FALSE, warning=FALSE, include=FALSE}
all_data_season_order_kept = all_data
all_data_season_order_kept$Season = factor(all_data_season_order_kept$Season, levels = season_order)

plot_ly(all_data_season_order_kept, x = ~Season, y = ~Attacks, color = ~Name, type = 'scatter', mode = 'lines+markers') %>%
    layout(xaxis = list(title = "Season"),
           yaxis = list(title = "Number of Attacks"))
```